---
fixtures:
  repositories:
    common: "git://github.com/simp/pupmod-simp-common.git"
    simplib: 'git://github.com/simp/pupmod-simp-simplib'
    stdlib: "git://github.com/simp/puppetlabs-stdlib.git"
  symlinks:
    activemq: "#{source_dir}"
